
   
version: '2'

services:

  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'

    volumes:
      - ./pssql_data:/var/lib/postgresql/data

    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=fs_node_boilerplate_local

